### ISSUE TITLE
`HRSemanticsRMW` invariant is violated in HermesRMWs TLA+ specification

### ISSUE THREAD

**Issue by will62794** [ease-lab/Hermes#1]
In the [HermesRMWs](https://github.com/ease-lab/Hermes/blob/282fae7114b99528fe922ec8ebe71d272c5dcd28/tla/HermesRMWs.tla) TLA+ specification,`HRSemanticsRMW` is [stated](https://github.com/ease-lab/Hermes/blob/282fae7114b99528fe922ec8ebe71d272c5dcd28/tla/HermesRMWs.tla#L244) as an invariant. This appears not to hold when model checking with TLC, even on a small model.

Here's a simple repro script that can be run from a clean directory:
```bash
#!/bin/sh
git clone https://github.com/ease-lab/Hermes.git
cd Hermes/tla
wget https://github.com/tlaplus/tlaplus/releases/download/v1.7.3/tla2tools.jar

echo "INIT HRInit" >> HermesRMWs.cfg
echo "NEXT HRNext" >>  HermesRMWs.cfg
echo "CONSTANTS" >>  HermesRMWs.cfg
echo "H_NODES = {33,44,55}" >> HermesRMWs.cfg
echo "H_MAX_VERSION = 2" >> HermesRMWs.cfg
echo "INVARIANT HRSemanticsRMW" >> HermesRMWs.cfg

java -cp tla2tools.jar tlc2.TLC -workers 4 HermesRMWs
```
TLC produces a 12-step counterexample ([hermes_cex.txt](https://github.com/ease-lab/Hermes/files/14776746/hermes_cex.txt)) in a few seconds.

I don't have a deep enough understanding of the underlying protocol to be clear on whether this is a bug in the algorithm or in the specification, but wanted to document this for reference, and see if you have any thoughts on this.

**Comment by akatsarakis** [comment]
Great catch!

I skimmed through the spec quickly, and I think it is missing the condition that when a node fails,
it must reset all previously received acks for RMWs. I will take a closer look later this week to double-check it.

<img width="342" alt="image" src="https://github.com/ease-lab/Hermes/assets/7034886/b161ed32-833b-4759-9229-5ce3d3741e00">


Thanks for reporting it :)

**Comment by akatsarakis** [comment]
Let me know if my last commit fixes your issue. 
[949229c](https://github.com/ease-lab/Hermes/commit/949229c238818509aed1435c46f9a76819ce2818)

**Comment by will62794** [comment]
Yes, that appears to fix it, thanks. 

After re-running the config above with your fix included, TLC reports no error:
```
$ java -cp tla2tools.jar tlc2.TLC -workers 6 HermesRMWs
TLC2 Version 2.18 of 20 March 2023 (rev: 3ea3222)
Warning: Please run the Java VM which executes TLC with a throughput optimized garbage collector by passing the "-XX:+UseParallelGC" property.
(Use the -nowarning option to disable this warning.)
Running breadth-first search Model-Checking with fp 50 and seed -8769381011494231749 with 6 workers on 8 cores with 4096MB heap and 64MB offheap memory [pid: 68489] (Mac OS X 10.16 x86_64, Oracle Corporation 16 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /private/tmp/bob/Hermes/tla/HermesRMWs.tla
Parsing file /private/tmp/bob/Hermes/tla/Hermes.tla
Parsing file /private/var/folders/f8/s3kg1k4d4fd6zkzkrw8xbk_80000gn/T/Integers.tla
Parsing file /private/var/folders/f8/s3kg1k4d4fd6zkzkrw8xbk_80000gn/T/FiniteSets.tla
Parsing file /private/var/folders/f8/s3kg1k4d4fd6zkzkrw8xbk_80000gn/T/Naturals.tla
Parsing file /private/var/folders/f8/s3kg1k4d4fd6zkzkrw8xbk_80000gn/T/Sequences.tla
Semantic processing of module Naturals
Semantic processing of module Integers
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module Hermes
Semantic processing of module HermesRMWs
Starting... (2024-03-28 15:30:00)
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2024-03-28 15:30:00.
Progress(18) at 2024-03-28 15:30:03: 478,550 states generated (478,550 s/min), 139,632 distinct states found (139,632 ds/min), 37,723 states left on queue.
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 4.7E-7
  based on the actual fingerprints:  val = 3.7E-7
7440935 states generated, 1427355 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 38.
The average outdegree of the complete state graph is 1 (minimum is 0, the maximum 10 and the 95th percentile is 3).
Finished in 26s at (2024-03-28 15:30:25)
```
Also, running in simulation mode with larger parameter `H_MAX_VERSION = 3` finds no error after about a minute or so, after generating ~150,768,921 states.

**Comment by akatsarakis** [comment]
Excellent! thanks again :)
